const menu = [
    {
      id: 1,
      title: 'Veg Manchuria',
      category: 'Veg Starters',
      type: 'veg',
      price: 150,
      img: './assets/VegManchuria.jpg',
      desc: `Serves 2 members`,
    },
    {
      id: 2,
      title: 'Paneer 65',
      category: 'Veg Starters',
      type: 'veg',
      price: 180,
      img: './assets/Paneer65.jpg',
      desc: `Serves 2 members`,
    },
    {
      id: 3,
      title: 'Paneer Manchuria',
      category: 'Veg Starters',
      type: 'veg',
      price: 180,
      img: './assets/paneermanchuria.jpg',
      desc: `Serves 2 members`,
    },
    {
      id: 4,
      title: 'Chilli Paneer',
      category: 'Veg Starters',
      type: 'veg',
      price: 180,
      img: './assets/ChilliPaneer.jpg',
      desc: `Serves 2 members `,
    },
    {
      id: 5,
      title: 'Crispy Corn',
      category: 'Veg Starters',
      type: 'veg',
      price: 130,
      img: './assets/crispycorn.jpg',
      desc: `Serves 2 members `,
    },
    {
      id: 6,
      title: 'French Fries',
      category: 'Veg Starters',
      type: 'veg',
      price: 130,
      img: './assets/Frenchfries.jpg',
      desc: `Serves 2 members`,
    },
    {
      id: 7,
      title: 'Chicken 65',
      category: 'Non-Veg Starters',
      type: 'non-veg',
      price: 180,
      img: './assets/chicken65.jpg',
      desc: `Serves 2 members `,
    },
    {
      id: 8,
      title: 'Chilly Chicken',
      category: 'Non-Veg Starters',
      type: 'non-veg',
      price: 180,
      img: './assets/Chillichicken.jpg',
      desc: `Serves 2 members `,
    },
    {
      id: 9,
      title: 'Chicken Manchuria',
      category: 'Non-Veg Starters',
      type: 'non-veg',
      price: 180,
      img: './assets/chickenmanchuria.jpg',
      desc: `Serves 2 members`,
    },
    {
        id: 10,
        title: 'Lemon Chicken',
        category: 'Non-Veg Starters',
        type: 'non-veg',
        price: 180,
        img: './assets/LemonChicken.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 11,
        title: 'Pepper Chicken',
        category: 'Non-Veg Starters',
        type: 'non-veg',
        price: 200,
        img: './assets/pepperchicken.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 12,
        title: 'Chicken Lollipop',
        category: 'Non-Veg Starters',
        type: 'non-veg',
        price: 180,
        img: './assets/chickenlollipop.jpg',
        desc: `6pc.`,
      },
      {
        id: 13,
        title: 'Chicken Wings',
        category: 'Non-Veg Starters',
        type: 'non-veg',
        price: 180,
        img: './assets/chickenwings.jpg',
        desc: `10pc`,
      },
      {
        id: 14,
        title: 'Chicken Guljera',
        category: 'Non-Veg Starters',
        type: 'non-veg',
        price: 180,
        img: './assets/chickengulzar.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 15,
        title: 'Chilli Prawn',
        category: 'Non-Veg Starters',
        type: 'non-veg',
        price: 200,
        img: './assets/Chilli-Prawns.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 16,
        title: 'Loose Prawn',
        category: 'Non-Veg Starters',
        type: 'non-veg',
        price: 220,
        img: './assets/looseprawn.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 17,
        title: 'Apollo Fish',
        category: 'Non-Veg Starters',
        type: 'non-veg',
        price: 240,
        img: './assets/apollofish.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 18,
        title: 'Chicken Fry Biryani',
        type: 'non-veg',
        category: 'Biryani',
        price: 220,
        img: './assets/chickenfry.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 19,
        title: 'Chicken Dum Biryani',
        category: 'Biryani',
        type: 'non-veg',
        price: 210,
        img: './assets/chickendum.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 20,
        title: 'Chicken Mughalai Biryani',
        category: 'Biryani',
        type: 'non-veg',
        price: 240,
        img: './assets/chickenmughalai.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 21,
        title: 'Chicken Lollipop Biryani',
        category: 'Biryani',
        type: 'non-veg',
        price: 220,
        img: './assets/chickenlollipopbiryani.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 22,
        title: 'Prawn Fry Biryani',
        category: 'Biryani',
        type: 'non-veg',
        price: 240,
        img: './assets/prawnfry.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 23,
        title: 'Veg Biryani',
        category: 'Biryani',
        type: 'veg',
        price: 150,
        img: './assets/vegbiryani.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 24,
        title: 'Paneer Biryani',
        category: 'Biryani',
        type: 'veg',
        price: 180,
        img: './assets/paneerbiryani.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 25,
        title: 'Special Paneer Biryani',
        category: 'Biryani',
        type: 'veg',
        price: 220,
        img: './assets/specialpaneerbiryani.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 26,
        title: 'Special Veg Biryani',
        category: 'Biryani',
        type: 'veg',
        price: 180,
        img: './assets/specialveg.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 27,
        title: 'Veg Fried Rice',
        category: 'Fried Rice',
        type: 'veg',
        price: 150,
        img: './assets/vegfriedrice.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 28,
        title: 'Paneer Fried Rice',
        category: 'Fried Rice',
        type: 'veg',
        price: 180,
        img: './assets/paneerfriedrice.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 29,
        title: 'Special Paneer Fried Rice',
        category: 'Fried Rice',
        type: 'veg',
        price: 220,
        img: './assets/specialpaneerfried.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 30,
        title: 'Special Veg Fried Rice',
        category: 'Fried Rice',
        type: 'veg',
        price: 220,
        img: './assets/specialvegfriedrice.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 31,
        title: 'Egg Fried Rice',
        category: 'Fried Rice',
        type: 'non-veg',
        price: 180,
        img: './assets/eggfriedrice.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 32,
        title: 'Chicken Fried Rice',
        category: 'Fried Rice',
        type: 'non-veg',
        price: 200,
        img: './assets/chickenfriedrice.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 33,
        title: 'Special Chicken Fried Rice',
        category: 'Fried Rice',
        type: 'non-veg',
        price: 230,
        img: './assets/specialchickenfried.jpg',
        desc: `Serves 2 members`,
      },
      {
        id: 34,
        title: 'Chicken Schezwan Fried Rice',
        category: 'Fried Rice',
        type: 'non-veg',
        price: 200,
        img: './assets/schezwan.jpg',
        desc: `Serves 2 members`,
      },
      

  ];
  export default menu;
  